### ISSUE TITLE
直接跳到搜索了，是啥原因?

### ISSUE THREAD

**Issue by bosconb** [hanzichi/hanzi2pinyin#1]
![image](https://user-images.githubusercontent.com/47100031/58758033-08020380-8548-11e9-915c-f09f0c70106d.png)

**Comment by lessfish** [comment]
没安装上吧？购买了 powerpack 没？

**Comment by bosconb** [comment]
> 没安装上吧？购买了 powerpack 没？

装上了，确定
![image](https://user-images.githubusercontent.com/47100031/58770541-1f8dca80-85e2-11e9-8d60-1f8b56177d7e.png)

4.01版，有powerpack的

![image](https://user-images.githubusercontent.com/47100031/58770550-30d6d700-85e2-11e9-8e40-d6dc99ad163c.png)

**Comment by lessfish** [comment]
@bosconb 升级到 4 了啊，我还用着 3，有空看下是不是大版本升级的问题

**Comment by lessfish** [comment]
@bosconb 我升级了下，没问题呀，你看下 `/usr/local/bin/python` 是不是不存在，默认用这个 python2 跑的

ps：感觉升级后的 UI 难看了啊

**Comment by bosconb** [comment]
> /usr/local/bin/python

好象没有，我是python3.7……

**Comment by bosconb** [comment]
d

> @bosconb 我升级了下，没问题呀，你看下 `/usr/local/bin/python` 是不是不存在，默认用这个 python2 跑的
> 
> ps：感觉升级后的 UI 难看了啊

除了变丑了，感觉不到大变化

What’s New
Version 4.0.1:

General changes:
Fix Welcome Window backup and migration logs to correctly show bright text in dark mode
Add additional nil checking into internal search
Change bundle id to "com.runningwithcrayons.Alfred" for now and future
Future proofs major versions which will now share macOS App Support, cache folders etc
Removes name dependency when using AppleScript to call Alfred, now you can use tell application id "com.runningwithcrayons.Alfred" to search
Note: Also added a "Show Alfred" workflow object which should be used where possible instead of AppleScript call backs
Add "Welcome" window when first launching Alfred
Pre-activation of Powerpack
Settings backup and migration of older preferences
Configure macOS permissions
Hardened runtime support for macOS
Improved, higher performance application caching for Alfred's file search
Prevent multiple copies of Alfred from running if, for example, a workflow accidentally attempts to re-launch Alfred as a new process
Hotkey display will now track the current keyboard layout (i.e. ⌘L in British layout will now correctly show ⌘N when switching the keyboard to Dvorak)
Improve secondary-view input field / selection list text copy behaviour to match Alfred's main search field
E.g. allows for copy partial selected search term, or partial selected summary text from clipboard history viewer without overriding with "copy entire item" action
Show correct fallback text when query is dynamically updated, for example, pressing
after a calculation to equate the answer
Make 'alfred preferences' correctly match result to show Alfred's preferences in Alfred's default results
Standardise big hat drawing between Workflows and Remote preferences when no workflow or page is selected
Make QuickLook previews change dynamically when changing result item in Alfred's Default Results and File System Navigation
Migrate and modernise many icons into PaintCode
Show "this does nothing" notification when double clicking an alfredpreferences file
Fix locale and macOS language discovery to correctly format dates
Fix applies to all places where dates can be used, e.g. Snippets, Workflow placeholders, Contacts
Update mechanism for storing and reading preferences sync folder to prefs.json in Alfred's Application Support folder
JSON contains 'current' value, written at startup to help external scripts find Alfred's preferences if synced
Note, for the time being, the syncfolder is still written to the preferences plist for workflow libraries which may rely on this
Migrate remaining http links to https (to force encryption where unspecified)
e.g. Contact URLs, Workflow website, Remote page examples, 1Password, user proxy settings
Also certain labels throughout the preferences now correctly show https

**Comment by lessfish** [comment]
@bosconb 你电脑上是没 python2 么？应该是我的 `/usr/local/bin/python` 是 py2，你的是 py3 导致的？反正 py3 是跑不起来的

**Comment by lessfish** [comment]
或者你可以试试双击 workflow，然后命令改成 `/usr/local/bin/python2`

**Comment by bosconb** [comment]
> 或者你可以试试双击 workflow，然后命令改成 `/usr/local/bin/python2`

好吧，改了照样打不开，对python深恶痛绝，就此别过

**Comment by lessfish** [comment]
@bosconb 哈哈，真的有需求的话，可以自己写个，没几行代码的，兄台走好～
